config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'messages#new'
  resources :messages, only: [:index, :new, :create]

  namespace :api do
    get '/messages/random', to: 'messages_random#show'
    resources :messages, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    render json: Message.all
  end

  # def show
  #   render json: Message.find(params[:id])
  # end
end

app/controllers/api/messages_random_controller.rb
class Api::MessagesRandomController < ApplicationController
  def show
    render json: Message.order('RANDOM()').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages =  Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:success] = "Your message has been sent! It will appear on John's MagicMirror soon."
      redirect_to new_message_path
    else
      flash.now[:danger] = "Try again."
      render :new
    end
  end

  private
  def message_params
    params.require(:message).permit(:text, :sender)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGkEV-UCg1ELAFRB_lm6Q6Y_iF_Ca5jRE0c7mTpmUYKqSw5mwe' %>
    <title>MessagesForJohn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="flashes">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <button type="button" class="close" data-dismiss='alert'>x</button>
          <%= sanitize(message) %>
          <% end %>
        </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="#">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGkEV-UCg1ELAFRB_lm6Q6Y_iF_Ca5jRE0c7mTpmUYKqSw5mwe" width="70" height="70" class="d-inline-block align-top" alt="">
  </a>
  <a href= "<%=new_message_path%>">Send a message</a>
</nav>

<div class="container" style="padding-top:50px">
    <h2>Messages</h2>
    <hr>
    <hr>
    <% @messages.each do |m| %>
      <div><%= m.text %></div><br>
      <% end %>
</div>

app/views/messages/new.html.erb
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="#">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGkEV-UCg1ELAFRB_lm6Q6Y_iF_Ca5jRE0c7mTpmUYKqSw5mwe" width="70" height="70" class="d-inline-block align-top" alt="">
  </a>
  <a href= "<%=messages_path%>">See all messages</a>
</nav>

<div class="container" style="padding:50px">
    <%= form_for @message do |f| %>
    <h3>Write your messsage here:</h3>
    <div style="padding-bottom:15px">
      <%= f.text_area :text, size: "50x15" %><br>
    </div>
      <div style="padding-bottom:15px">
        <%= f.label :sender %>
        <%= f.text_field :sender %><br>
      </div>
      <div>
        <%= f.submit class: 'btn btn-primary'%>
    </div>
    <% end %><br>
  </div>
</div>